#!/bin/bash

# Create the Programs file if it does not already exist
mkdir -p /home/$USER/bin
touch /home/$USER/bin/Programs
echo "Programs:" >> /home/$USER/bin/Programs
echo "" >> /home/$USER/bin/Programs
echo "Flatpaks:" >> /home/$USER/bin/Programs

# Install programs listed in the Programs file
while read line; do
    if [[ $line == "Programs:" ]] || [[ $line == "Flatpaks:" ]]; then
        continue
    fi
    if [[ $line == *".flatpak"* ]]; then
        flatpak install -y $line
    else
        sudo apt-get install -y $line
    fi
done < /home/$USER/bin/Programs
