#!/bin/bash

if [[ ! -f /home/$USER/bin/Programs_install.txt ]]; then
    # Create the Programs install file if it does not already exist
    mkdir -p /home/$USER/bin
    touch /home/$USER/bin/Programs_install.txt
fi

if [[ ! -f /home/$USER/bin/Programs_uninstall.txt ]]; then
    # Create the Programs uninstall file if it does not already exist
    touch /home/$USER/bin/Programs_uninstall.txt
fi

if [[ ! -f /home/$USER/bin/Flatpaks_install.txt ]]; then
    # Create the Flatpaks install file if it does not already exist
    touch /home/$USER/bin/Flatpaks_install.txt
fi

# Check if flatpak is already installed. If not, install it.
if ! command -v flatpak > /dev/null; then
    echo "flatpak is not installed, installing it now..."
    sudo apt-get install -y flatpak
fi

# Install programs listed in Programs_install.txt
while read line; do
  if [ -z "$line" ]; then
    continue
  fi
    sudo apt-get install -y $line
done < /home/$USER/bin/Programs_install.txt

# Uninstall programs listed in Programs_uninstall.txt
while read line; do
  if [ -z "$line" ]; then
    continue
  fi
    sudo apt-get remove -y $line
done < /home/$USER/bin/Programs_uninstall.txt

# Install flatpaks listed in Flatpaks_install.txt
while read line; do
  if [ -z "$line" ]; then
    continue
  fi
    flatpak install -y $line
done < /home/$USER/bin/Flatpaks_install.txt
