#!/bin/bash

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
sudo apt-get update -y && sudo apt-get dist-upgrade -y

mkdir -p /home/$USER/bin/Programs

# Download the files from the repository
wget https://raw.githubusercontent.com/wvufantim/LMprograms/master/Programs_install -O /home/$USER/bin/Programs/Programs_install
wget https://raw.githubusercontent.com/wvufantim/LMprograms/master/Programs_uninstall -O /home/$USER/bin/Programs/Programs_uninstall
wget https://raw.githubusercontent.com/wvufantim/LMprograms/master/Flatpaks_install -O /home/$USER/bin/Programs/Flatpaks_install

# Check if flatpak is already installed. If not, install it.
if ! command -v flatpak > /dev/null; then
    echo "flatpak is not installed, installing it now..."
    sudo apt-get install -y flatpak
fi

# Install programs listed in Programs_install
while read line; do
  if [ -z "$line" ]; then
    continue
  fi
    sudo apt-get install -y $line
done < /home/$USER/bin/Programs/Programs_install

# Uninstall programs listed in Programs_uninstall
while read line; do
  if [ -z "$line" ]; then
    continue
  fi
    sudo apt-get purge -y $line
done < /home/$USER/bin/Programs/Programs_uninstall

# Install flatpaks listed in Flatpaks_install
while read line; do
  if [ -z "$line" ]; then
    continue
  fi
    flatpak install -y $line >/dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "Error: Failed to install $line"
    else
        echo "Success: $line installed"
    fi
done < /home/$USER/bin/Programs/Flatpaks_install
