#!/bin/bash

# Check if nala is already installed. If not, install it.
if ! command -v nala > /dev/null; then
    echo "nala is not installed, installing it now..."
    sudo apt-get install -y nala
fi

# Create aliases for nala so that it can be used as a replacement for apt and apt-get
echo "alias apt='nala'" >> ~/.bashrc
echo "alias apt-get='nala'" >> ~/.bashrc
source ~/.bashrc

while true; do
    echo "1. Install Programs"
    echo "2. Uninstall Programs"
    echo "3. Install Flatpaks"
    echo "4. Uninstall Flatpaks"
    echo "5. Exit"
    read -p "Please select an option: " option
    case $option in
        1)
            read -p "Enter programs to install (separated by spaces): " programs_to_install
            for program in $programs_to_install; do
                # Check if the program is already installed
                if ! dpkg-query -W -f='${Status}' "$program" 2>/dev/null | grep -c "ok installed" > /dev/null; then
                    # If the program is not already installed, install it
                    sudo nala install -y "$program"
                fi
            done
            ;;
        2)
            read -p "Enter programs to uninstall (separated by spaces): " programs_to_uninstall
            for program in $programs_to_uninstall; do
                # Check if the program is already installed
                if dpkg-query -W -f='${Status}' "$program" 2>/dev/null | grep -c "ok installed" > /dev/null; then
                    # If the program is already installed, uninstall it
                    sudo nala remove -y "$program"
                fi
            done
            ;;
        3)
            read -p "Enter flatpaks to install (separated by spaces): " flatpaks_to_install
            for flatpak in $flatpaks_to_install; do
                # Check if the flatpak is already installed
                if ! flatpak list --app --columns=application | grep -q "$flatpak"; then
                    # If the flatpak is not already installed, install it
                    flatpak install -y flathub "$flatpak"
                fi
            done
            ;;
        4)
            read -p "Enter flatpaks to uninstall (separated by spaces): " flatpaks_to_uninstall
            for flatpak in $flatpaks_to_uninstall; do
                # Check if the flatpak is already installed
                if flatpak list --app --columns=application | grep -q "$flatpak"; then
                    # If the flatpak is already installed, uninstall it
                    flatpak uninstall -y "$flatpak"
                fi
            done
            ;;
        5)
            exit
            ;;
        *)
            echo "Invalid option"
            ;;
    esac
done
