#!/bin/bash

# Install nala if it's not already installed
if ! command -v nala > /dev/null; then
    echo "nala is not installed, installing it now..."
    sudo apt-get install -y nala
fi

# Create aliases for nala
echo "alias apt='nala'" >> ~/.bashrc
echo "alias apt-get='nala'" >> ~/.bashrc
source ~/.bashrc

while true; do
    echo "1. Install Programs"
    echo "2. Uninstall Programs"
    echo "3. Install Flatpaks"
    echo "4. Uninstall Flatpaks"
    echo "5. Exit"
    read -p "Please select an option: " option
    case $option in
        1)
            read -p "Enter programs to install (separated by spaces): " programs_to_install
            for program in $programs_to_install; do
                if ! dpkg-query -W -f='${Status}' "$program" 2>/dev/null | grep -c "ok installed" > /dev/null; then
                    sudo nala install "$program"
                fi
            done
            ;;
        2)
            read -p "Enter programs to uninstall (separated by spaces): " programs_to_uninstall
            for program in $programs_to_uninstall; do
                if dpkg-query -W -f='${Status}' "$program" 2>/dev/null | grep -c "ok installed" > /dev/null; then
                    sudo nala remove "$program"
                fi
            done
            ;;
        3)
            read -p "Enter flatpaks to install (separated by spaces): " flatpaks_to_install
            for flatpak in $flatpaks_to_install; do
                if ! flatpak list --app --columns=application | grep -q "$flatpak"; then
                    flatpak install flathub "$flatpak"
                fi
            done
            ;;
        4)
            read -p "Enter flatpaks to uninstall (separated by spaces): " flatpaks_to_uninstall
            for flatpak in $flatpaks_to_uninstall; do
                if flatpak list --app --columns=application | grep -q "$flatpak"; then
                    flatpak uninstall "$flatpak"
                fi
            done
            ;;
        5)
            exit
            ;;
        *)
            echo "Invalid option"
            ;;
    esac
done
